version: "3.8"

services:
  expo:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: npx expo start --tunnel
