version: "3.8"

services:
  expo:
    build: .
    ports:
      - "8081:8081" # Metro bundler
      - "19000:19000" # Expo dev
      - "19001:19001" # WebSocket
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: expo start --tunnel
